#pragma once

#include "bootloader.h"
#include "efi.h"
#include "elfloader.h"
#include "graphics.h"
#include "kernel.h"
#include "stdfunc.h"
#include "asmloader.h"
#include "asmkernel.h"
#include "descriptor.h"
#include "handler.h"
#include "keyboard.h"
#include "pic.h"
#include "stl.h"
#include "global.h"
#include <stddef.h>
#include <cstdint>
#include <stdarg.h>